export * from './Home'
export * from './Origins'
export * from './References'
export * from './Slide2'
export * from './Slide5'
export * from './Slide6'
export * from './Support'
export * from './WhatIs'
